# Methods & Pipeline tab — always visible; transparent per-stage status -------
tab_methods_ui <- function(id, cfg) {
  ns <- NS(id)
  nav_panel(
    title = "Methods & Pipeline", icon = icon("diagram-project"),
    div(class = "container py-3",
      h3(cfg$project$name %||% "RNA-seq analysis"),
      div(class = "banner",
          tags$b("What this is. "),
          "An interactive report for the TUY35595 mouse DRG/nerve RNA-seq study ",
          "(nucleus pulposus (MINP) / nerve-injury model). ",
          "Sections are released stage by stage; the status of each is shown below and updated as work proceeds."),
      h4("Pipeline"),
      tags$ul(
        tags$li(tags$b("Sequencing: "), "Illumina NovaSeq X, paired-end 2×151 bp."),
        tags$li(tags$b("Primary analysis: "), cfg$project$pipeline %||%
                "nf-core/rnaseq v3.19.0 (Trim Galore → STAR → Salmon), mouse GRCm39, Ensembl 116."),
        tags$li(tags$b("Quantification: "), "Gene- and transcript-level count matrices (Salmon), analysed in parallel."),
        tags$li(tags$b("Differential expression: "), "DESeq2 and edgeR/limma-voom, reported side-by-side."),
        tags$li(tags$b("Enrichment: "), "GSEA over GO (BP/CC/MF) and KEGG (clusterProfiler)."),
        tags$li(tags$b("Cell-type deconvolution: "), "bulk cell-type proportions estimated with ",
                tags$b("MuSiC"), " from a published mouse DRG single-cell reference ",
                "(Renthal et al. 2020, GEO GSE154659; naive cells, 18 cell types).")
      ),
      h4("Design & samples"),
      tags$ul(
        tags$li("Conditions: ", tags$b("MINP"), " (nucleus pulposus), ", tags$b("SNI"),
                " (spared nerve injury), ", tags$b("Sham"), " — each in male and female."),
        tags$li("MINP and Sham: n = 3 per sex. ",
                tags$b("SNI: n = 1 per sex"),
                " — shown in QC/PCA but excluded from differential-expression contrasts (no replication)."),
        tags$li("Reference level for contrasts: ", tags$b("Sham"), ".")
      ),

      h4("Batch correction — why"),
      div(class = "banner",
        "The three biological replicates are three ", tags$b("processing cohorts"),
        " run on different dates (surgery → harvest → dissection → RNA extraction), with cohort 3 ",
        "roughly three weeks after cohorts 1–2. In the uncorrected PCA the ",
        tags$b("cohort (replicate) explained ~60% of PC1"), " — the largest axis of variance — ",
        "far more than the MINP-vs-Sham biology (~0%). That is a batch effect, confirmed by the ",
        "study's own planning sheet (below)."),
      tags$ul(
        tags$li(tags$b("Differential expression: "), "replicate is modelled as an additive batch ",
                "covariate (", tags$code("~ 0 + group + replicate"), "), so each contrast is adjusted for cohort."),
        tags$li(tags$b("PCA / boxplots: "), "the replicate effect is removed with ",
                tags$code("limma::removeBatchEffect"), " (condition and sex preserved)."),
        tags$li(tags$b("Sex chromosomes: "), "chrX/chrY genes are removed in the corrected analysis so ",
                "sex does not dominate and MINP-vs-Sham structure can show."),
        tags$li(tags$b("Sequencing depth: "), "library-size differences (e.g. Sham females were sequenced ",
                "~1.67× deeper than males) are removed by DESeq2 size-factor / edgeR TMM normalisation as a ",
                "per-sample offset — not a design term. This is validated by label permutation and equal-depth ",
                "down-sampling (100% sensitivity on known sex genes, ~99.98% specificity, 94% DEG recovery at ",
                "equal depth): see the QC ", tags$b("“Depth & power”"), " panel."),
        tags$li(tags$b("SNI: "), "a separate experiment (different operator, different injury model) — excluded from DE.")
      ),
      tags$table(class = "table table-sm table-bordered",
        tags$thead(tags$tr(lapply(c("Cohort (replicate)","Surgery","Harvest","RNA extraction","Samples"),
                                  function(h) tags$th(h)))),
        tags$tbody(
          tags$tr(tags$td("1"), tags$td("Feb 17"), tags$td("Feb 24"), tags$td("Mar 2"),  tags$td("MINP/Sham · M1 & F1")),
          tags$tr(tags$td("2"), tags$td("Feb 18"), tags$td("Feb 25"), tags$td("Mar 3"),  tags$td("MINP/Sham · M2 & F2")),
          tags$tr(tags$td("3"), tags$td("Mar 9"),  tags$td("Mar 16"), tags$td("Mar 18"), tags$td("MINP/Sham · M3 & F3")),
          tags$tr(tags$td("SNI"), tags$td("—"), tags$td("—"), tags$td("separate operator / model"), tags$td("SNI M & F")))),
      div(class = "mb-3",
        tags$a(href = "docs/BulkSeq_plan_2026.xlsx", download = "BulkSeq_plan_2026.xlsx",
               class = "btn btn-outline-secondary btn-sm",
               icon("file-excel"), " Download the sequencing planning sheet (source of the cohort dates)")),

      h4("Contrasts"),
      tags$ul(lapply(unname(CONTRAST_LABELS), function(x) tags$li(x))),
      h4("Release status"),
      uiOutput(ns("status_table")),
      div(class = "text-muted small mt-3",
          "Note: significance thresholds and gene-set selections shown in later tabs are exploratory and may be finalised with the study team."),

      tags$hr(),
      h4("Methods (manuscript format)"),
      div(class = "small", style = "line-height:1.55; max-width:900px;",
        tags$p(tags$b("Animals and study design. "),
          "Bulk RNA sequencing was performed on mouse dorsal root ganglia (DRG) and nerve tissue from three ",
          "conditions — MINP (nucleus pulposus application), Sham, and spared nerve injury (SNI) — in both sexes. ",
          "The MINP and Sham groups comprised n = 3 mice per sex (12 samples); SNI comprised n = 1 per sex ",
          "(2 samples), included in quality control and exploratory ordination but excluded from ",
          "differential-expression contrasts owing to the absence of replication. Libraries were sequenced on an ",
          "Illumina NovaSeq X instrument (paired-end, 2 × 151 bp), yielding 34.9–63.3 million read pairs per ",
          "sample (mean 46.7 million)."),
        tags$p(tags$b("Read processing, alignment and quantification. "),
          "Data was processed using nf-core/rnaseq v3.19.0 (doi: 10.5281/zenodo.1400710) of the nf-core collection ",
          "of workflows (Ewels et al., 2020), utilising reproducible software environments from the Bioconda ",
          "(Grüning et al., 2018) and Biocontainers (da Veiga Leprevost et al., 2017) projects, orchestrated with ",
          "Nextflow v25.04.7 (Di Tommaso et al., 2017). Reads were adapter- and quality-trimmed with Trim Galore ",
          "v0.6.10 (Cutadapt v4.9; Martin, 2011), removing a mean of 3.3% of bases, and aligned to the mouse ",
          "reference genome (GRCm39, Ensembl release 116; Cunningham et al., 2022) with STAR v2.7.11b ",
          "(Dobin et al., 2013). Transcript- and gene-level expression was quantified with Salmon v1.10.3 ",
          "(Patro et al., 2017) and imported with tximport/tximeta v1.20.1 (Soneson et al., 2015)."),
        tags$p(tags$b("Quality control. "),
          "Per-sample metrics were aggregated with MultiQC (Ewels et al., 2016). Across the 14 samples, STAR mapped ",
          "98.4–99.0% of reads (mean 98.8%), of which 92.2–94.7% (mean 93.7%) mapped uniquely; ribosomal RNA content ",
          "was low (0.09–0.55%, mean 0.21%); reads were predominantly exonic (~77%; Qualimap v2.3, Okonechnikov ",
          "et al., 2016); the 5′/3′ coverage bias was 1.15–1.27 (mean 1.20); duplication was 19.7–27.7% ",
          "(mean 23.4%; Picard MarkDuplicates v3.1.1); and GC content was 48–50%. Read distribution, strandedness and ",
          "duplication were additionally assessed with RSeQC v5.0.2 (Wang et al., 2012), SAMtools v1.21 ",
          "(Danecek et al., 2021) and dupRadar v1.32.0 (Sayols et al., 2016)."),
        tags$p(tags$b("Filtering and normalisation. "),
          "Analyses were performed in R v4.5.2. Low-count genes were removed with edgeR::filterByExpr, retaining ",
          "19,356 of 78,348 annotated genes for the 12-sample MINP/Sham analysis. Library size and composition were ",
          "normalised using DESeq2 median-of-ratios size factors (Love et al., 2014) and edgeR trimmed-mean-of-M-values ",
          "(TMM) factors (Robinson & Oshlack, 2010). Sham females were sequenced ~1.67-fold more deeply than Sham males; ",
          "this was absorbed by normalisation (DESeq2 size factors 1.35 vs 0.79; normalised total counts female/male ",
          "≈ 0.98), with TMM factors ≈ 1.0 indicating no composition bias."),
        tags$p(tags$b("Differential expression. "),
          "Differential expression was assessed with DESeq2 v1.50.2 (Love et al., 2014) and, in parallel, edgeR v4.8.2 / ",
          "limma-voom v3.66.0 (Robinson et al., 2010; Ritchie et al., 2015; Law et al., 2014), with Sham as reference. ",
          "Five contrasts were tested: MINP vs Sham (sexes pooled), MINP vs Sham within each sex, Sham male vs Sham ",
          "female, and MINP male vs MINP female. The uncorrected model was ~ 0 + group; a batch-corrected model added ",
          "the processing cohort as an additive covariate (~ 0 + group + replicate) and excluded chrX/chrY genes. ",
          "P-values were adjusted by the Benjamini–Hochberg false-discovery rate (Benjamini & Hochberg, 1995); genes with ",
          "adjusted p < 0.05 were considered differentially expressed. At the gene level (DESeq2, adjusted p < 0.05), the ",
          "batch- and sex-chromosome-corrected analysis identified 16, 6, 35, 240 and 27 DEGs for the MINP-vs-Sham, ",
          "MINP-male-vs-Sham-male, MINP-female-vs-Sham-female, Sham-male-vs-Sham-female and MINP-male-vs-MINP-female ",
          "contrasts, respectively (vs 10, 0, 18, 111 and 19 uncorrected)."),
        tags$p(tags$b("Batch effect. "),
          "The three biological replicates corresponded to processing cohorts prepared on different dates. In the ",
          "uncorrected principal-component analysis (DESeq2 variance-stabilising transformation, top 1,000 variable genes, ",
          "prcomp), processing cohort dominated PC1 (40.5% of variance), exceeding the biological condition; removing ",
          "chrX/chrY retained the cohort separation on PC1 (43.2%) while collapsing the sex axis, confirming a cohort ",
          "batch effect. For visualisation only (never in the differential-expression models), the cohort effect was ",
          "removed with limma::removeBatchEffect (Ritchie et al., 2015); after correction PC1 accounted for 26.2% of variance."),
        tags$p(tags$b("Validation of the sex signal. "),
          "To confirm the Sham female-vs-male differences were biological rather than a depth artefact, the comparison ",
          "(6 samples, 19,124 tested genes) was validated three ways. Sensitivity was 100% on a gold-standard positive set ",
          "of the five Y-chromosome genes (Ddx3y, Uty, Eif2s3y, Kdm5d, Uba1y) and Xist, all detected with large effect ",
          "sizes (Xist adjusted p ≈ 1.7 × 10⁻¹⁵²). Specificity, estimated by re-testing all random 3-versus-3 sample ",
          "relabellings, yielded a median of 4 spurious DEGs (≈ 0.02%; ≈ 99.98% specificity) versus 31 for the true split; ",
          "the single relabelling that produced many (303) coincided with the processing cohort. Down-sampling every library ",
          "to equal depth (30.7 million reads; edgeR::thinCounts) recovered 94% of DEGs (29/31) with log2 fold-change ",
          "concordance r = 0.97 and 100% gold-standard sensitivity retained."),
        tags$p(tags$b("Gene-set enrichment. "),
          "Gene-set enrichment analysis (Subramanian et al., 2005) was performed with clusterProfiler v4.18.4 ",
          "(Wu et al., 2021; fgsea backend v1.36.2, Korotkevich et al., 2021) over Gene Ontology (biological process, ",
          "cellular component, molecular function; Ashburner et al., 2000) and KEGG (Kanehisa & Goto, 2000) gene sets, ",
          "ranking genes by the DESeq2 Wald statistic, with identifier mapping via org.Mm.eg.db v3.22.0. Leading-edge ",
          "(core-enrichment) genes are reported for each significant set."),
        tags$p(tags$b("Cell-type deconvolution. "),
          "Cell-type composition of each bulk sample was estimated by reference-based deconvolution with MuSiC v1.0.0 ",
          "(multi-subject weighted non-negative least squares; Wang et al., 2019). The reference was a published mouse DRG ",
          "single-nucleus atlas (Renthal et al., 2020; GEO GSE154659), restricted to naive C57BL/6 nuclei (16,859 cells) ",
          "and to 18 cell types with ≥ 20 nuclei. Bulk gene-level raw counts were symbol-matched to the reference ",
          "(22,095 shared genes, 19,666 used) and deconvolved for all 14 samples (proportions summing to one). ",
          "Proportions were compared for every contrast using Wilcoxon rank-sum and Welch t-tests with Benjamini–Hochberg ",
          "correction; no cell type differed significantly between MINP and Sham (adjusted p ≈ 1)."),
        tags$p(tags$b("Cross-species analysis (rat & macaque). "),
          "To benchmark the mouse findings against well-powered and phylogenetically distant DRG, two external bulk ",
          "RNA-seq datasets were processed with the identical nf-core/rnaseq v3.19.0 workflow: rat DRG (67 samples; ",
          "spared-nerve-injury / skin-lesion / naïve × sex × DRG level, upper vs lower) aligned to ",
          tags$i("Rattus norvegicus"), " GRCr8 (Ensembl release 116), and macaque DRG (12 samples; ipsilateral / ",
          "contralateral / control nerve transection × sex) aligned to ", tags$i("Macaca fascicularis"),
          " 6.0 (Ensembl 116). Gene-level counts (STAR/Salmon) were analysed with DESeq2 using a ~0 + group design: ",
          "24 rat contrasts (12 comparison types computed within each DRG level) and 12 macaque contrasts, each also ",
          "recomputed with sex-chromosome genes removed. Genes were mapped to mouse via biomaRt one-to-one orthologues ",
          "(Durinck et al., 2009; 18,711 rat–mouse and 15,321 macaque–mouse pairs). Cross-species concordance was ",
          "quantified as Pearson/Spearman correlation of log2 fold-changes over shared orthologues, with same-direction ",
          "DEG overlap; a conserved nerve-injury signature (~279 genes) was defined as significant and concordant in ",
          "rat (lower-DRG SNI) and macaque (ipsi) with matching mouse direction. Cell-type composition was deconvolved ",
          "in each species with MuSiC against the same Renthal reference after collapsing ortholog-mapped counts to mouse ",
          "symbols. An integrated cross-species PCA combined all 93 samples over the 11,296 orthologues shared by all three ",
          "species (variance-stabilised counts), with a per-species gene-wise z-scored (“aligned”) variant to remove the ",
          "between-species baseline and expose shared condition structure."),
        tags$p(tags$b("Software and visualisation. "),
          "Figures used ggplot2 v4.0.3 (Wickham, 2016), pheatmap v1.0.13, ggVennDiagram v1.5.7 and UpSetR v1.4.1, and ",
          "plotly v4.12.0; the interactive report was built with Shiny/bslib and DT v0.34.0.")
      ),
      h5("References"),
      tags$ol(class = "small text-muted", style = "line-height:1.35;",
        tags$li("Ewels PA, Peltzer A, Fillinger S, et al. The nf-core framework for community-curated bioinformatics pipelines. Nat Biotechnol. 2020;38:276–278."),
        tags$li("Di Tommaso P, Chatzou M, Floden EW, et al. Nextflow enables reproducible computational workflows. Nat Biotechnol. 2017;35:316–319."),
        tags$li("Grüning B, Dale R, Sjödin A, et al. Bioconda: sustainable and comprehensive software distribution for the life sciences. Nat Methods. 2018;15:475–476."),
        tags$li("da Veiga Leprevost F, Grüning B, Alves Aflitos S, et al. BioContainers: an open-source and community-driven framework for software standardization. Bioinformatics. 2017;33:2580–2582."),
        tags$li("Martin M. Cutadapt removes adapter sequences from high-throughput sequencing reads. EMBnet.journal. 2011;17:10–12. (Trim Galore: Krueger F, Babraham Bioinformatics.)"),
        tags$li("Dobin A, Davis CA, Schlesinger F, et al. STAR: ultrafast universal RNA-seq aligner. Bioinformatics. 2013;29:15–21."),
        tags$li("Patro R, Duggal G, Love MI, Irizarry RA, Kingsford C. Salmon provides fast and bias-aware quantification of transcript expression. Nat Methods. 2017;14:417–419."),
        tags$li("Soneson C, Love MI, Robinson MD. Differential analyses for RNA-seq: transcript-level estimates improve gene-level inferences. F1000Research. 2015;4:1521."),
        tags$li("Cunningham F, Allen JE, Allen J, et al. Ensembl 2022. Nucleic Acids Res. 2022;50:D988–D995."),
        tags$li("Ewels P, Magnusson M, Lundin S, Käller M. MultiQC: summarize analysis results for multiple tools and samples in a single report. Bioinformatics. 2016;32:3047–3048."),
        tags$li("Wang L, Wang S, Li W. RSeQC: quality control of RNA-seq experiments. Bioinformatics. 2012;28:2184–2185."),
        tags$li("Okonechnikov K, Conesa A, García-Alcalde F. Qualimap 2: advanced multi-sample quality control for high-throughput sequencing data. Bioinformatics. 2016;32:292–294."),
        tags$li("Sayols S, Scherzinger D, Klein H. dupRadar: a Bioconductor package for the assessment of PCR artifacts in RNA-Seq data. BMC Bioinformatics. 2016;17:428."),
        tags$li("Danecek P, Bonfield JK, Liddle J, et al. Twelve years of SAMtools and BCFtools. GigaScience. 2021;10:giab008."),
        tags$li("Love MI, Huber W, Anders S. Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2. Genome Biol. 2014;15:550."),
        tags$li("Robinson MD, McCarthy DJ, Smyth GK. edgeR: a Bioconductor package for differential expression analysis of digital gene expression data. Bioinformatics. 2010;26:139–140."),
        tags$li("Robinson MD, Oshlack A. A scaling normalization method for differential expression analysis of RNA-seq data. Genome Biol. 2010;11:R25."),
        tags$li("Ritchie ME, Phipson B, Wu D, et al. limma powers differential expression analyses for RNA-sequencing and microarray studies. Nucleic Acids Res. 2015;43:e47."),
        tags$li("Law CW, Chen Y, Shi W, Smyth GK. voom: precision weights unlock linear model analysis tools for RNA-seq read counts. Genome Biol. 2014;15:R29."),
        tags$li("Benjamini Y, Hochberg Y. Controlling the false discovery rate: a practical and powerful approach to multiple testing. J R Stat Soc B. 1995;57:289–300."),
        tags$li("Subramanian A, Tamayo P, Mootha VK, et al. Gene set enrichment analysis. Proc Natl Acad Sci USA. 2005;102:15545–15550."),
        tags$li("Wu T, Hu E, Xu S, et al. clusterProfiler 4.0: A universal enrichment tool for interpreting omics data. The Innovation. 2021;2:100141."),
        tags$li("Korotkevich G, Sukhov V, Budin N, et al. Fast gene set enrichment analysis. bioRxiv. 2021. (fgsea)"),
        tags$li("Ashburner M, Ball CA, Blake JA, et al. Gene Ontology: tool for the unification of biology. Nat Genet. 2000;25:25–29."),
        tags$li("Kanehisa M, Goto S. KEGG: Kyoto Encyclopedia of Genes and Genomes. Nucleic Acids Res. 2000;28:27–30."),
        tags$li("Carlson M. org.Mm.eg.db: Genome wide annotation for Mouse. Bioconductor R package v3.22.0."),
        tags$li("Wang X, Park J, Susztak K, Zhang NR, Li M. Bulk tissue cell type deconvolution with multi-subject single-cell expression reference (MuSiC). Nat Commun. 2019;10:380."),
        tags$li("Renthal W, Tochitsky I, Yang L, et al. Transcriptional reprogramming of distinct peripheral sensory neuron subtypes after axonal injury. Neuron. 2020;108:128–144."),
        tags$li("Durinck S, Spellman PT, Birney E, Huber W. Mapping identifiers for the integration of genomic datasets with the R/Bioconductor package biomaRt. Nat Protoc. 2009;4:1184–1191."),
        tags$li("Wickham H. ggplot2: Elegant Graphics for Data Analysis. 2nd ed. Springer; 2016."),
        tags$li("Kolde R. pheatmap: Pretty Heatmaps. R package v1.0.13."),
        tags$li("Conway JR, Lex A, Gehlenborg N. UpSetR: an R package for the visualization of intersecting sets. Bioinformatics. 2017;33:2938–2940."),
        tags$li("Gao CH, Yu G, Cai P. ggVennDiagram: an intuitive, easy-to-use, and highly customizable R package to generate Venn diagram. Front Genet. 2021;12:706907."),
        tags$li("R Core Team. R: A language and environment for statistical computing. R Foundation for Statistical Computing; 2025."),
        tags$li("Chang W, Cheng J, Allaire JJ, et al. shiny: Web Application Framework for R. R package.")
      )
    )
  )
}

tab_methods_server <- function(id, cfg) {
  moduleServer(id, function(input, output, session) {
    output$status_table <- renderUI({
      rows <- lapply(cfg$stages_ordered, function(s) {
        tags$tr(tags$td(tags$b(s$title)),
                tags$td(status_chip(s$status)),
                tags$td(if (isTRUE(s$released)) "Released" else "Internal / pending"))
      })
      tags$table(class = "table table-sm",
        tags$thead(tags$tr(tags$th("Stage"), tags$th("Status"), tags$th("Release"))),
        tags$tbody(rows))
    })
  })
}
